/**
 * Ids are generated by the application, not the database. A folder's path
 * embeds its own id, so the id has to exist before the row is written.
 */
export abstract class IdGeneratorPort {
  abstract generate(): string;
  /** Unguessable token for a public share link. */
  abstract generateToken(): string;
}
